{% set version = "0.1.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vetiver
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vetiver_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vetiver/vetiver_{{ version }}.tar.gz
  sha256: f95e2f496fa3b28f7c9d16709996b7c7c29a8bd908d7282b9fe3651b430ad76b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bundle
    - r-butcher
    - r-cli
    - r-fs
    - r-generics
    - r-glue
    - r-hardhat
    - r-lifecycle
    - r-magrittr >=2.0.3
    - r-pins >=1.0.0
    - r-plumber >=1.0.0
    - r-purrr
    - r-rapidoc
    - r-readr >=1.4.0
    - r-renv
    - r-rlang >=1.0.0
    - r-tibble
    - r-vctrs
    - r-withr
  run:
    - r-base
    - r-bundle
    - r-butcher
    - r-cli
    - r-fs
    - r-generics
    - r-glue
    - r-hardhat
    - r-lifecycle
    - r-magrittr >=2.0.3
    - r-pins >=1.0.0
    - r-plumber >=1.0.0
    - r-purrr
    - r-rapidoc
    - r-readr >=1.4.0
    - r-renv
    - r-rlang >=1.0.0
    - r-tibble
    - r-vctrs
    - r-withr

test:
  requires:
    - r-testthat >=3.0.0
    - r-caret
    - r-dplyr
    - r-flexdashboard
    - r-mlr3
    - r-mlr3learners
    - r-modeldata
    - r-ranger
    - r-rmarkdown >=2.12
    - r-rsconnect
    - r-slider >=0.2.2
    - r-vdiffr
    - r-workflows
    - r-xgboost
    - r-yardstick
  source_files:
    - tests/testthat/
    - tests/testthat.R
  commands:
    - $R -e "library('vetiver')"                                                                # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', c('location', 'check', 'fail'))"           # [not win]
    - "\"%R%\" -e \"library('vetiver')\""                                                       # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', c('location', 'check', 'fail'))\""  # [win]

about:
  home: https://vetiver.tidymodels.org/, https://github.com/tidymodels/vetiver
  license: MIT
  summary: The goal of 'vetiver' is to provide fluent tooling to version, share, deploy, and monitor a trained model. Functions handle both recording and checking the model's input data prototype, and predicting from a remote API endpoint. The 'vetiver' package is extensible, with generics that can support many kinds of
    models.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler
